- name: backend config
  hosts: backend
  become: true
  tasks:

  - name: install packages
    apt:
      name:
        - python3
        - python3-pip
        - mariadb-client
        - gcc
        - build-essential
        - libmariadb-dev    
        - python3-dev
        - haproxy
        - pkg-config
      state: present
      update_cache: yes

  - name: Install Python packages for Django
    pip:
      name:
        - django
        - mysqlclient
        - gunicorn
      executable: pip3

  - name: Ensure destination directory exists
    file:
      path: /opt/webapp
      state: directory
      owner: vagrant
      group: vagrant
      mode: "0755"
      
  - name: Copy Django project files
    copy:
      src: files/webapp2/
      dest: /opt/webapp/
      owner: vagrant
      group: vagrant
      mode: '0755'

  - name: Run Django migrations
    command: python3 manage.py makemigrations notes
    args:  
      chdir: "/opt/webapp"
    become_user: vagrant

  - name: Run Django migrations
    command: python3 manage.py migrate
    args:  
      chdir: "/opt/webapp"
    become_user: vagrant
  
  - name: Collect static files
    command: python3 manage.py collectstatic --noinput
    args:
      chdir: "/opt/webapp/"
    become_user: vagrant

  - name: Deploy systemd unit for Gunicorn
    copy:
      dest: /etc/systemd/system/gunicorn.service
      owner: root
      group: root
      mode: "0644"
      content: |
        [Unit]
        Description=Gunicorn service for Django Notes App
        After=network.target

        [Service]
        WorkingDirectory=/opt/webapp/
        ExecStart=/usr/local/bin/gunicorn myproject.wsgi:application \
          --bind 192.168.56.20:8000 \
          --workers 3 \
          --access-logfile - --error-logfile -
        User=vagrant
        Restart=on-failure

        [Install]
        WantedBy=multi-user.target

  - name: Restart gunicorn
    systemd:
      name: gunicorn
      daemon_reload: true
      enabled: true
      state: restarted

