# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Используем бокс Ubuntu 22.04 из официального облака
    config.vm.box = "generic/ubuntu2204"
     
    # Настройка виртуальной машины
    config.vm.provider "virtualbox" do |vb|
      # ОЗУ
      vb.memory = "2048"
      # Ядра
      vb.cpus = 2
  
      # Создаем диски
      (1..6).each do |i|
        unless File.exist?("disk#{i}.vdi")
        vb.customize [
          "createhd",
          "--filename", "disk#{i}.vdi",
          "--size", 1024 # Размер диска в MB (1GB)
        ]
        end
        vb.customize [
          "storageattach", :id,
          "--storagectl", "SATA Controller",
          "--port", i,
          "--device", 0,
          "--type", "hdd",
          "--medium", "disk#{i}.vdi"
        ]
      end
    end
  
    # Настройка сети
    #config.vm.network "private_network", ip: "192.168.56.10"
  
    # Загрузочный скрипт (provision)
    config.vm.provision "file", source: "./start_raid.sh", destination: "/home/vagrant/start_raid.sh"
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get upgrade
      apt-get install -y mdadm smartmontools hdparm gdisk
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
      sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      #chmod +x /home/vagrant/start_raid.sh
      #/home/vagrant/start_raid.sh
    SHELL
  end
